# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20161020_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='name',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
    ]
