# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20161024_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created']},
        ),
    ]
