# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20161025_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
