# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_remove_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.Protocol'),
        ),
    ]
