# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_protocol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='timedelta',
            new_name='daydelta',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='time',
            field=models.TimeField(default=datetime.time(7, 30)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='appointments.Appointment'),
        ),
    ]
