# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_auto_20161113_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='message_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.MessageAction'),
        ),
    ]
