# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_reply_message_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='rule',
        ),
    ]
