# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 22:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_remove_protocol_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='rule',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
