# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_protocol_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('lookup_type', models.CharField(choices=[('exact', 'Exact match'), ('iexact', 'Case-insensitive exact match'), ('contains', 'Case-sensitive containment test'), ('icontains', 'Case-insensitive containment test')], max_length=32)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='rule',
        ),
        migrations.AddField(
            model_name='constraint',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='appointments.Protocol'),
        ),
    ]
