# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_auto_20161118_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='field',
            field=models.CharField(choices=[('procedure_description', 'procedure_description'), ('appointment_scheduled_service', 'appointment_scheduled_service')], max_length=32),
        ),
    ]
