# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_auto_20161118_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='protocol',
        ),
        migrations.AddField(
            model_name='appointment',
            name='protocols',
            field=models.ManyToManyField(to='appointments.Protocol'),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='lookup_type',
            field=models.CharField(choices=[('exact', 'exact'), ('iexact', 'Case-insensitive exact'), ('contains', 'contains'), ('icontains', 'Case-insensitive contains')], max_length=32),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='clients',
            field=models.ManyToManyField(related_name='protocols', to='appointments.Client'),
        ),
    ]
