# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_auto_20161118_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='content_tail',
            field=models.TextField(blank=True),
        ),
    ]
