# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_messagetemplate_content_tail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_facility',
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together=set([('client', 'name')]),
        ),
    ]
