# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_auto_20161126_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.Facility'),
        ),
    ]
