# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_appointment_appointment_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='operator_type',
            field=models.CharField(choices=[('and', 'and'), ('or', 'or')], default='and', max_length=32),
        ),
    ]
