# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_auto_20161207_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='negate',
            field=models.BooleanField(default=False),
        ),
    ]
