# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_constraint_negate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='negate',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='operator_type',
        ),
        migrations.AddField(
            model_name='protocol',
            name='constraint_relationship',
            field=models.CharField(blank=True, help_text='Please use {$constraint_id} for Constraint, & for AND, | for OR, ~ for NOT, and () for grouping. Sample: {$1} & ~({$2} | {$3}).', max_length=255),
        ),
    ]
