# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0025_auto_20161211_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='datetime_format',
            field=models.CharField(choices=[('%d %b %Y %I:%M%p', '25 Oct 2006 02:30PM'), ('%b %d, %Y %I:%M%p', 'Oct 25, 2006 02:30PM'), ('%B %d, %Y %I:%M%p', 'October 25, 2006 02:30PM'), ('%m/%d/%Y %I:%M%p', '10/25/2006 02:30PM'), ('%Y-%m-%d %H:%M', '2006-10-25 14:30'), ('%Y-%m-%d', '2006-10-25'), ('%m/%d/%Y %H:%M', '10/25/2006 14:30'), ('%m/%d/%Y', '10/25/2006'), ('%m/%d/%y %H:%M', '10/25/06 14:30'), ('%m/%d/%y', '10/25/06')], default='%m/%d/%Y %I:%M%p', max_length=32),
        ),
    ]
