# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0029_auto_20170130_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='content_tail_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='content_tail_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
