# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0031_auto_20170220_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='for_appointment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
