# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0032_message_for_appointment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelog',
            options={'ordering': ['created']},
        ),
    ]
