# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0033_auto_20170228_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_provider',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='provider_npi_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='provider_specialty',
        ),
    ]
