# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0034_auto_20170314_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('provider_id', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_npi_id', models.CharField(max_length=64)),
                ('provider_specialty', models.CharField(blank=True, max_length=64, null=True)),
                ('office_hours', models.CharField(max_length=128)),
                ('contact_details', models.CharField(max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.Client')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.Provider'),
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together=set([('client', 'provider_npi_id')]),
        ),
    ]
