# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 00:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0037_dayafterappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayafterappointment',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
